# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- feature/*
- master

pool:
  name: Demo

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.300'
  targetRuntime: 'linux-x64'

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
    # - script: dotnet build --configuration $(buildConfiguration)
    #   displayName: 'dotnet build $(buildConfiguration)'
    
    # - task: Npm@1
    #   displayName: 'Client Tests'
    #   inputs:
    #     command: 'ci'
    #     workingDir: 'ClientApp'
    #     verbose: true

    - script: dotnet publish --no-build -v detailed -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
      displayName: Publish Project 

    # - task: Npm@1
    #   displayName: 'Client Tests'
    #   inputs:
    #     command: 'custom'
    #     workingDir: 'ClientApp'
    #     customCommand: 'run test'
    
    # - task: PublishBuildArtifacts@1
    #   inputs:
    #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #     ArtifactName: 'drop'
    #     publishLocation: 'Container'
