# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- feature/*
- master

pool:
  name: Demo

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.300'
  targetRuntime: 'linux-x64'

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

    - task: Npm@1
      displayName: 'Client Tests'
      inputs:
        command: 'ci'
        workingDir: 'ClientApp'
        verbose: true

    - script: dotnet publish -f $(dotNetFramework) -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
      displayName: Publish Project 

 
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
  
    # - task: DotNetCoreCLI@2
    #   displayName: Publish Projects
    #   inputs:
    #     command: 'publish'
    #     publishWebProjects: true
    #     arguments: '--configuration $(buildConfiguration) -f $(dotNetFramework) --runtime $(targetRuntime) --self-contained -o $(Build.ArtifactStagingDirectory)'
    #     zipAfterPublish: true

- stage: 'DeploytoDev'
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      name: Demo
    environment: 'dev'
    strategy: 
      runOnce:
        deploy:
          steps:
            # No need to explicitly pass the connection details.
           - task: AzureRmWebAppDeployment@4
             inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'AzureCon'
              appType: 'webAppLinux'
              WebAppName: 'bermtecdev'
              packageForLinux: '$(System.DefaultWorkingDirectory)/_Raghupatik.dotnetdemo/drop'